server:
  port: 5000

graphql:
  debug: true
  playground: true
  introspection: true
  autoSchemaFile: _schema.graphql
  dateScalarMode: isoDate
  depthLimit: 5

db:
  type: postgres
  host: localhost
  port: 5432
  username: hellwest
  password: hellwest
  database: hostel
  logging: true
  synchronize: true
  migrationsRun: false
